describe('Failed login', () => {
    it('Fails to log in with wrong email toast', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('wrongemail@@.com')
        cy.get('[placeholder="password"]')
            .type("wrongpassword")
        cy.get('#login-button')
            .click()
        cy.get('.react-toast-notifications__toast__content')
            // .should('be.visible')
            .should('have.text', "The email address is badly formatted.")
    })
})

describe('Successful login', () => {
    it('Logins to warehouse', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.react-toast-notifications__toast__content')
            // .should('be.visible')
            .should('have.text', "Successfully logged in")
    })
})

describe('Renders navigation', () => {
    it('Renders nav for admin', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(1)')
            .should('be.visible')
        cy.get('.navbar-nav > :nth-child(2)')
            .should('be.visible')
        cy.get('.navbar-nav > :nth-child(3)')
            .should('be.visible')
        cy.get('.navbar-nav > :nth-child(4)')
            .should('be.visible')
        cy.get('.navbar-nav > :nth-child(5)')
            .should('be.visible')
        cy.get('.navbar-nav > :nth-child(6)')
            .should('be.visible')
        cy.get('.navbar-nav > :nth-child(7)')
            .should('be.visible')
        cy.get('.navbar-nav > :nth-child(8)')
            .should('be.visible')
        cy.get('.navbar-nav > :nth-child(9)')
            .should('be.visible')
    })
})

describe('Nav opens modules', () => {
    it('Products module opens', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(1) > .text-white')
            .click()
        cy.get("h3")
            .should('have.text', 'PRODUCTS')
    });
    it('Place order module opens', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(2) > .text-white')
            .click()
        cy.get("h3")
            .should('have.text', 'PLACE ORDER')
    })
    it('ORDERS module opens', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(3) > .text-white')
            .click()
        cy.get("h3")
            .should('have.text', 'ORDERS')
    })
    it('ADD PRODUCT module opens', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(4) > .text-white')
            .click()
        cy.get("h3")
            .should('have.text', 'ADD PRODUCT')
    })
    it('ADD USER module opens', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(5) > .text-white')
            .click()
        cy.get("h3")
            .should('have.text', 'ADD USER')
    })
    it('Transfer products module opens', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(6) > .text-white')
            .click()
        cy.get("h3")
            .should('have.text', 'TRANSFER PRODUCTS')
    })
    it('Manage admins module opens', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(7) > .text-white')
            .click()
        cy.get("h3")
            .should('have.text', 'MANAGE ADMINS')
    })
    it('Invoices module opens', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(8) > .text-white')
            .click()
        cy.get("h3")
            .should('have.text', 'INVOICES')
    })
    it('Add invoice module opens with closing toast', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.react-toast-notifications__toast__dismiss-icon')
            .click()
        cy.get(':nth-child(9) > .text-uppercase')
            .click()
        cy.get("h3")
            .should('have.text', 'ADD INVOICE')
    })
})
describe('Logs out', () => {
    it('Successful log out', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.button-logout')
            .click()
        cy.get(':nth-child(1) > .react-toast-notifications__toast > .react-toast-notifications__toast__dismiss-button > .react-toast-notifications__toast__dismiss-icon')
            .click()
        cy.get('.react-toast-notifications__toast__content')
            .should('have.text', 'Signed out')
    })
})
describe('Edits product', () => {
    it('Successfully edited product', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(1)')
            .click()
        cy.get(':nth-child(1) > :nth-child(4) > div > .button-white')
            .click()
        cy.get('#categoryId')
            .should('be.visible')
        cy.get('#name')
            .should('be.visible')
        cy.get('#user')
            .should('be.visible')
        cy.get('#warehouse')
            .should('be.visible')
        cy.get('.button-green')
            .should('be.visible')
    })
})

describe('Placing order', () => {
    it('Successfully added products and placed order', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.wait(200)
        cy.get('.navbar-nav > :nth-child(2)')
            .click()
        cy.get('tbody > tr').eq(4)
            .click({force: true})
        cy.get('.align-items-center > :nth-child(2) > :nth-child(1)')
            .should('be.visible')
        cy.get('#Lolipop')
            .should('be.visible')
        cy.get('.react-toast-notifications__toast__dismiss-icon')
            .click()
        cy.get('.button-green-wide')
            .click()
        cy.get('.react-toast-notifications__toast__content')
            .should("have.text", "Order placed successfully")
    })
})

describe('Fulfilling placed order', () => {
    it('Successfully fulfills placed order', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(3)')
            .click()
        cy.get(':nth-child(7) > tbody > :nth-child(2) > :nth-child(3)')
            .should("have.text", 'warehouse@test.com')
        cy.get('#root > :nth-child(8)')
            .click()
        cy.get(':nth-child(1) > .react-toast-notifications__toast > .react-toast-notifications__toast__dismiss-button > .react-toast-notifications__toast__dismiss-icon')
            .click()
        cy.get('.react-toast-notifications__toast__content')
            .should('have.text', 'Order deleted')
    })
})

describe('Successfully transfering products', () => {
    it('Successfully adds products to transfer', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(6)')
            .click()
        cy.wait(300)
        cy.get('#Table')
            .click({force : true})
        cy.get(':nth-child(4) > :nth-child(2) > :nth-child(1)')
            .should('have.text', 'Table')
    })
    it('Successfully submits transfer', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(6)')
            .click()
        cy.get('#Table')
            .click({force: true})
        cy.get(':nth-child(4) > :nth-child(2) > :nth-child(1)')
            .should('have.text', 'Table')
        cy.get('#toUserMenu')
            .select("user")
        cy.get('.button-green-wide')
            .click()
        cy.get(':nth-child(1) > .react-toast-notifications__toast > .react-toast-notifications__toast__dismiss-button > .react-toast-notifications__toast__dismiss-icon')
            .click()
        cy.get('.react-toast-notifications__toast__content')
            .should('have.text', 'Transfer submitted')
    })
})

describe('Managing admins', () => {
    it('Switches user to admin', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(7)')
            .click()
        cy.get('tbody > :nth-child(1) > :nth-child(2)')
            .should("have.text", "No")
        cy.get('#user')
            .click()
        cy.get('tbody > :nth-child(1) > :nth-child(2)')
            .should("have.text", "Yes")
    })
    it('Switches admin to user', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(7)')
            .click()
        cy.get('#user')
            .click()
        cy.get('tbody > :nth-child(1) > :nth-child(2)')
            .should("have.text", "No")
    })
})

describe('Invoices', () => {
    it('Should open invoice', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.navbar-nav > :nth-child(8)')
            .click()
        cy.get(':nth-child(1) > :nth-child(6) > .button-green')
            .click()
        cy.get('.centered-h1')
            .should("be.visible")
    })
})
describe('Adding invoices', () => {
    it('Should add to list', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.react-toast-notifications__toast__dismiss-icon')
            .click()
        cy.get('.navbar-nav > :nth-child(9)')
            .click()
        cy.get('[value="Eggs"]')
            .click({force : true})
        cy.get('.align-items-center > :nth-child(2) > :nth-child(1)')
            .should("have.text", "Eggs")
    })
    it('Form should show', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[placeholder="email"]')
            .type('warehouse@test.com')
        cy.get('[placeholder="password"]')
            .type("123456789")
        cy.get('#login-button')
            .click()
        cy.get('.react-toast-notifications__toast__dismiss-icon')
            .click()
        cy.get('.navbar-nav > :nth-child(9)')
            .click()
        cy.get('[value="Eggs"]')
            .click({force : true})
        cy.get('#contractor-input')
            .should('be.visible')
        cy.get('#date-input')
            .should("be.visible")
        cy.get('#invoice-number-input')
            .should("be.visible")
        cy.get('#fromUserMenu')
            .should("be.visible")
        cy.get('.button-green-wide')
            .should("be.visible")
    })
})
